//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_1110_ADO_v1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-6MR6T3L5\\SQLEXPRESS;Initial Catalog=Northwind;Integrated Secur" +
            "ity=True")]
        public string MyNorthwindConn {
            get {
                return ((string)(this["MyNorthwindConn"]));
            }
            set {
                this["MyNorthwindConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-6MR6T3L5\\SQLEXPRESS;Initial Catalog=AdventureWorksDW2019;Integ" +
            "rated Security=True")]
        public string MyAdventureWorksDW2019 {
            get {
                return ((string)(this["MyAdventureWorksDW2019"]));
            }
            set {
                this["MyAdventureWorksDW2019"] = value;
            }
        }
    }
}
